

spring.application.name=empleados

# ============================================
# CONNEXION A MYSQL
# ============================================
spring.datasource.url=jdbc:mysql://localhost:3306/empleados_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ============================================
# CONFIGURATION JPA / HIBERNATE
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ============================================
# CONFIGURATION PARA JSP
# ============================================
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

#Context path de la app
server.servlet.context-path=/empleados












# ============================================
# CONEXIÓN A SQL SERVER
# ============================================
# Nota: Usamos Usuario 'sa' para evitar el error de 'Connection reset'
# que ocurre con integratedSecurity=true si falta el archivo .dll de Windows.
#spring.datasource.url=jdbc:sqlserver://ANONIMOUS\\EMDIGITAL;databaseName=empleados_db;encrypt=false;trustServerCertificate=true
#spring.datasource.username=root
#spring.datasource.password=admin
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ============================================
# CONFIGURACIÓN JPA / HIBERNATE
# ============================================
#spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

# ============================================
# CONFIGURACIÓN PARA JSP
# ============================================
#spring.mvc.view.prefix=/WEB-INF/views/
#spring.mvc.view.suffix=.jsp